name: feature_flags_client
description: A Generic Feature Flags Client Interface.
version: 1.0.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0

dev_dependencies:
  test: ^1.31.0
  very_good_analysis: ^10.2.0
